FROM apache/hive:4.0.1
COPY mysql-connector-java-8.0.28.jar /opt/hive/lib/

# RUN curl -L https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.28.tar.gz | tar xz \
#     && mv mysql-connector-java-8.0.28/mysql-connector-java-8.0.28.jar /opt/hive/lib/ \
#     && rm -rf mysql-connector-java-8.0.28*
